# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./env/app
    volumes:
      - ./app/:/code
    depends_on:
      - db
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=remarcable
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
